services:
  payload:
    container_name: h-blog
    image: node:22-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm add -g pnpm && pnpm install && pnpm dev"
    depends_on:
      - postgres
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 114514homo
      DATABASE_URI: blog-postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: blog
      PAYLOAD_SECRET: fdASKFHNJKAS%DSI&&R324

  postgres:
    container_name: blog-postgres
    restart: always
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 114514homo
      POSTGRES_DB: blog

volumes:
  pgdata:
  node_modules: