services:
  payload:
    image: ghcr.io/huanhq99/h-blog:latest
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environments:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_URI: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: blog
      PAYLOAD_SECRET: YOUR_SECRET_HERE

  postgres:
   restart: always
   image: postgres:16-alpine
   volumes:
     - pgdata:/var/lib/postgresql/data
   ports:
     - "5432:5432"
   environments:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: blog

volumes:
  pgdata:
  node_modules:
