name: Build and Push Docker image to GHCR

on:
  push:
    branches: [ main ]  # 或你想触发的分支
  workflow_dispatch:     # 手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # 必须允许写 packages 才能推送到 ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-image-name
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.image }} .

      - name: Push Docker image
        run: |
          docker push ${{ steps.vars.outputs.image }}
